Upgrade thrift revision number to 0.10.0
Default thrift revision is 0.9.1 which gives the following compilation
error with gcc 6 (I am using 6.2.0)

src/generate/t_java_generator.cc:2830:14: error: operands to ?: have
different types ‘bool’ and ‘std::basic_ostream<char>’
        first ? first = false : indent(f_service_) << "else ";
                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Upgrading to the latest version with the same major
number, 0.9.3, yields the compilation error below. SSLV3
has been deprecated because of security issues (see e.g.
                http://disablessl3.com/)

src/thrift/transport/TSSLSocket.cpp: In constructor 'apache::thrift::transport::SSLContext::SSLContext(
  const apache::thrift::transport::SSLProtocol&)': src/thrift/transport/TSSLSocket.cpp:143:37: error: 'SSLv3_method' was not declared in this scope
ctx_ = SSL_CTX_new(SSLv3_method());
^
Makefile:1280 : la recette pour la cible « src/

Upgrading to 0.10.0 works  fine